FROM node:latest as build-stage
WORKDIR /app
COPY package*.json /app
RUN yarn install
COPY ./ /app/
RUN yarn build

FROM nginx:latest
COPY --from=build-stage /app/build/ /usr/share/nginx/html
EXPOSE 80/tcp
